### ISSUE TITLE
Tokens secretos no codigo

### ISSUE THREAD

**Issue by vitor-mafra** [coelhobf/ufv_ru_bot#1]
Seu arquivo .env contem todas as chaves necessarias para tweetar na sua conta do Twitter. Se essas sao mesmo chaves validas, recomendo que voce gere novas imediatamente, para que ninguem mal intencionado use sua conta sem sua  autorizacao. Uma solucao que uso para o bot da UFMG eh ler essas chaves em um arquivo .txt que nao esta disponivel no github

**Comment by coelhobf** [comment]
Opa, obrigado pelo toque, o código não ta mais usando o .env, eu coloco as keys diretamente com enviroment da heroku, eu fiz um commit com pressa e acabou subindo, vou corrigir.
